name: CI

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: echo hello > world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact-2
          path: world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact-3
          path: world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: you-artifact
          path: world.txt

      - name: Delete (specific, glob disabled)
        uses: ./
        with:
          name: my-artifact
          useGlob: false

      - name: Delete (pattern, glob enabled)
        uses: ./
        with:
          name: my-*

      - name: Delete (specific, glob enabled, and token specified)
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: you-artifact
